flask-blog/app/views/main.py
from flask import Blueprint,render_template,current_app,request,redirect,url_for
from app.models import Posts,User
from app.extensions import cache

main = Blueprint('main',__name__)

@main.route('/')
#缓存存活时间
def index():
    return redirect(url_for('main.page_show',page=1))

#设置缓存记忆
@cache.memoize(timeout=100)
@main.route('/page_show/<int:page>')
# @cache.cached(timeout=100,key_prefix='index')
def page_show(page):
    #返回按时间倒叙的当前页数的帖子数据
    pagination = Posts.query.filter_by(pid=0).order_by(Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)
    # 返回当前page的所有数据
    data = pagination.items
    return render_template('main/index.html',data=data,pagination=pagination)

@main.route('/test1/')
def test1():
    u = User.query.get(1)
    p = Posts.query.get(1)
    # id1用户收藏1号帖子
    u.favorite.append(p)

    # 查看用户1收藏了那些帖子
    print(u.favorite.all())

    # 1号帖子被哪些用户 收藏了
    # print(p.users.all())

    # 取消收藏
    # u.favorite.remove(p)
    return 'test'

flask-blog/app/views/posts.py
from flask import Blueprint,render_template,flash,url_for,redirect,jsonify
from app.forms import Posts as PostsForm
from flask_login import current_user
from app.models import Posts
from app.extensions import db

posts = Blueprint('posts',__name__)


#发表帖子的路由,methods一定要记得加上
@posts.route('/send_posts/',methods=['GET','POST'])
def send_posts():
    form = PostsForm()
    #对发表帖子的用户进行验证
    if form.validate_on_submit():
        # print('11')
        if current_user.is_authenticated:
            u = current_user._get_current_object()
            p = Posts(content=form.content.data,user=u)
            db.session.add(p)
            flash('帖子发表成功')
            return redirect(url_for('main.index'))
        else:
            flash('您还没有登录,请登录之后在发表')
            return redirect(url_for('user.login'))
    return render_template('posts/send_posts.html',form=form)

#收藏取消收藏
@posts.route('/favorite/<pid>')
def favorite(pid):
    try:
        if current_user.is_favorite(pid):
            current_user.remove_favorite(pid)
        else:
            current_user.add_favorite(pid)
        return jsonify({'res':200})
    except:
        return jsonify({'res': 500})

flask-blog/app/templates/main/index.html
{% extends 'common/base.html' %}
{% block title %}
    首页
{% endblock %}
{% block page_content %}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            {% for i in range(1,3) %}
                <div class="item {% if loop.first %}active{% endif %}" style="height: 400px;">
                    <img src="{{ url_for('static',filename='img/'+i|string+'.png') }}" alt="...">
                    <div class="carousel-caption">

                    </div>
                </div>
            {% endfor %}

        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    {#  以下为帖子的展示页面  #}
    {% for posts in data %}
        <div class="media">
            <div class="media-left media-middle">
                <a href="#">
                    <img height="150" class="media-object"
                         src="{{ url_for('static',filename='upload/'+posts.user.icon) }}"
                         alt="{{ posts.user.username }}">
                </a>
            </div>
            <div class="media-body">
                <h3 class="media-heading"><a href="#">超酷一镜到底创意倒放MV《串烧2017》</a><span
                        style="float: right;font-size: 14px">{{ moment(posts.timestamp).fromNow() }}</span></h3>
                {{ posts.content|safe }}
                {% if current_user.is_authenticated %}
                    <div onclick="favorite({{ posts.id }})" id="{{ posts.id }}" url="{{ url_for('posts.favorite',pid=posts.id) }}">{% if current_user.is_favorite(posts.id) %}取消收藏{% else %}收藏{% endif %}</div>
                {% endif %}
            </div>
        </div>
    {% endfor %}

    {#  导入分页的macro  #}
    {% from 'common/pagemacro.html' import page_show %}
    {{ page_show(pagination,'main.page_show') }}
{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        function favorite(pid){
            var doc = $('#'+pid);
            $.get(doc.attr('url'),function (data) {
                console.log('执行',data)
                if(doc.html() == '收藏'){
                    doc.html('取消收藏')
                }else{
                    doc.html('收藏')
                }
            })
        }
    </script>
{% endblock %}