flask-blog/app/views/main.py
from flask import Blueprint,render_template,current_app,request,redirect,url_for
from app.models import Posts,User
from app.extensions import cache

main = Blueprint('main',__name__)

@main.route('/')
#缓存存活时间
def index():
    return redirect(url_for('main.page_show',page=1))

#设置缓存记忆
@cache.memoize(timeout=100)
@main.route('/page_show/<int:page>')
# @cache.cached(timeout=100,key_prefix='index')
def page_show(page):
    #返回按时间倒叙的当前页数的帖子数据
    pagination = Posts.query.filter_by(pid=0).order_by(Posts.timestamp.desc()).paginate(page, current_app.config['PAGE_NUM'], False)
    # 返回当前page的所有数据
    data = pagination.items
    return render_template('main/index.html',data=data,pagination=pagination)

@main.route('/test1/')
def test1():
    u = User.query.get(1)
    p = Posts.query.get(1)
    # id1用户收藏1号帖子
    u.favorite.append(p)

    # 查看用户1收藏了那些帖子
    print(u.favorite.all())

    # 1号帖子被哪些用户 收藏了
    # print(p.users.all())

    # 取消收藏
    # u.favorite.remove(p)
    return 'test'

flask-blog/app/views/posts.py
from flask import Blueprint,render_template,flash,url_for,redirect,jsonify
from app.forms import Posts as PostsForm
from flask_login import current_user
from app.models import Posts
from app.extensions import db

posts = Blueprint('posts',__name__)


#发表帖子的路由,methods一定要记得加上
@posts.route('/send_posts/',methods=['GET','POST'])
def send_posts():
    form = PostsForm()
    #对发表帖子的用户进行验证
    if form.validate_on_submit():
        # print('11')
        if current_user.is_authenticated:
            u = current_user._get_current_object()
            p = Posts(content=form.content.data,user=u)
            db.session.add(p)
            flash('帖子发表成功')
            return redirect(url_for('main.index'))
        else:
            flash('您还没有登录,请登录之后在发表')
            return redirect(url_for('user.login'))
    return render_template('posts/send_posts.html',form=form)

#收藏取消收藏
@posts.route('/favorite/<pid>')
def favorite(pid):
    try:
        if current_user.is_favorite(pid):
            current_user.remove_favorite(pid)
        else:
            current_user.add_favorite(pid)
        return jsonify({'res':200})
    except:
        return jsonify({'res': 500})

flask-blog/app/views/user.py
from app.models import User
from flask import Blueprint,render_template,flash,url_for,redirect,current_app
from app.forms import Register,Login,Icon
from app.extensions import db,file,cache
from app.email import send_mail
from flask_login import login_user,logout_user,login_required,current_user
import os
from PIL import Image

user = Blueprint('user',__name__)

#注册
@user.route('/register/',methods=['GET','POST'])
def register():
    #实例化form
    form = Register()
    if form.validate_on_submit():
        # 实例化user模型类
        u = User(username=form.username.data,password=form.password.data,email=form.email.data)

        db.session.add(u)
        db.session.commit()
        # 生成token
        token = u.generate_token()
        send_mail('邮件激活',form.email.data,'activate',username=form.username.data,token=token)
        #提示用户注册信息
        flash('注册成功请去邮箱中激活')
        #跳转到登陆页面
        return redirect(url_for('user.login'))
    return render_template('user/register.html',form=form)

#激活
@user.route('/activate/<token>/')
def activate(token):
    if User.check_token(token):
        flash('激活成功请登录')
        return redirect(url_for('user.login'))
    else:
        flash('激活失败')
        return redirect(url_for('main.index'))

#登录
@user.route('/login/',methods=['GET','POST'])
def login():
    form = Login()
    if form.validate_on_submit():
        u = User.query.filter_by(username=form.username.data).first()
        # print(u.username)
        if not u:
            flash('该用户不存在')
        elif not u.confirm:
            flash('该用户没有激活')
        elif u.check_password_hash(form.password.data):
            # print('231')
            flash('登录成功')
            cache.clear()
            login_user(u,remember=form.remember.data)
            return redirect(url_for('main.index'))
        else:
            flash('请输入正确的密码')
    return render_template('user/login.html',form=form)

#登出
@user.route('/logout/')
def logout():
    cache.clear()
    logout_user()
    flash('退出成功！')
    return redirect(url_for('main.index'))
#生成新的名字
def new_name(shuffix,length=32):
    import string,random
    myStr = string.ascii_letters+'0123456789'
    return ''.join(random.choice(myStr) for i in range(length)) + shuffix




#修改头像
@user.route('/change_icon/',methods=['GET','POST'])
def change_icon():
    form = Icon()
    if form.validate_on_submit():
        shuffix = os.path.splitext(form.file.data.filename)[-1]
        #生成随机图片

        while True:
            newName = new_name(shuffix)
            if not os.path.exists(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],newName)):
                break
        file.save(form.file.data,name=newName)
        print(current_user.icon)

        if current_user.icon != 'default.jpg':
            # print('11313')
            os.remove(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],current_user.icon))

        # 执行缩放
        img = Image.open(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'], newName))
        img.thumbnail((300, 300))
        # 保存新的图片名称为新的图片的newname
        img.save(os.path.join(current_app.config['UPLOADED_PHOTOS_DEST'],  newName))

        current_user.email = form.email.data

        current_user.icon = newName
        db.session.add(current_user)
        flash('头像上传成功')



    img_url = file.url(current_user.icon)
    # print(img_url)
    return render_template('user/change_icon.html',form=form,img_url=img_url)

flask-blog/app/templates/common/base.html
{% extends 'bootstrap/base.html' %}
{% block title %}
    使用bootsrap
{% endblock %}
{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#"><span class="glyphicon glyphicon-signal" aria-hidden="true"></span></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('main.index') }}">首页 <span
                            class="sr-only">(current)</span></a></li>
                    <li><a href="{{ url_for('posts.send_posts') }}">电影</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="#"><img src="https://cs.vmovier.com/Uploads/Banner/2017/12/23/5a3d52d82724d.png" style="height: 30px ;width: 30px"  alt=""></a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true"
                               aria-expanded="false">个人中心 <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">个人信息</a></li>
                                <li><a href="{{ url_for('user.change_icon') }}">修改信息</a></li>
{#                                <li><a href="#">修改密码</a></li>#}
{#                                <li><a href="#">修改邮箱</a></li>#}
                                <li role="separator" class="divider"></li>
                                <li><a href="{{ url_for('user.logout') }}">退出登录</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('user.register') }}">注册</a></li>
                        <li><a href="{{ url_for('user.login') }}">登录</a></li>
                    {% endif %}
                </ul>
                <form class="navbar-form navbar-right">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">搜索</button>
                </form>
            </div><!-- /.navbar-collapse -->
        </div>
    </nav>


{% endblock %}
{% block content -%}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <strong></strong>{{ message }}
            </div>
        {% endfor %}
        {% block page_content %}

        {% endblock %}
    </div>
{%- endblock content %}
{% block scripts %}
    {{ super() }}
    {{ moment.include_moment() }}
    {{ moment.locale('zh-CN') }}
{% endblock %}

flask-blog/app/templates/common/pagemacro.html
{% macro page_show(pagination,urlFor) %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li {% if not pagination.has_prev %} class="disabled"{% endif %}>

                <a {% if pagination.has_prev %} href="{{ url_for(urlFor,page=pagination.prev_num) }}" {% endif %} aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% for page in pagination.iter_pages() %}
                {% if page %}
                <li {% if page==pagination.page %}class="active"{% endif %}><a href="{{ url_for(urlFor,page=page) }}">{{ page }}</a></li>
                {% else %}
                <li class="disabled"><a>...</a></li>
                {% endif %}
            {% endfor %}
            <li {% if not pagination.has_next %} class="disabled"{% endif %}>

                <a {% if pagination.has_next %} href="{{ url_for(urlFor,page=pagination.next_num) }}" {% endif %} aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}